# Generated by Django 3.2 on 2021-05-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaddress',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartaddress',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartpayment',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
