# Generated by Django 3.2 on 2021-05-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210513_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaddress',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cartaddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.country'),
        ),
        migrations.AlterField(
            model_name='cartaddress',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cartaddress',
            name='house_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cartaddress',
            name='postal_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cartaddress',
            name='street_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cartpayment',
            name='card_number',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='cartpayment',
            name='cvc',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='cartpayment',
            name='expiration_date',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
