# Generated by Django 3.2 on 2021-05-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210504_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='super_user',
        ),
    ]
